# Generated by Django 2.1.7 on 2020-03-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='权限名')),
                ('permission_url', models.CharField(blank=True, max_length=64, null=True, verbose_name='权限url')),
                ('permission_level', models.IntegerField(blank=True, null=True, verbose_name='权限等级')),
                ('permission_pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vue_shop.Permission', verbose_name='权限父ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色名')),
                ('role_desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='角色描述')),
                ('permission', models.ManyToManyField(blank=True, null=True, to='vue_shop.Permission', verbose_name='权限')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='vue_shop.Roles', verbose_name='角色'),
        ),
    ]
