# Generated by Django 2.1.7 on 2020-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_shop', '0002_auto_20200309_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=64, verbose_name='用户名'),
        ),
    ]
