# Generated by Django 2.2.4 on 2020-03-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vue_shop', '0003_auto_20200310_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='role',
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='vue_shop.Roles', verbose_name='角色'),
            preserve_default=False,
        ),
    ]
