# Generated by Django 2.1.7 on 2020-03-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vue_shop', '0004_auto_20200312_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vue_shop.Roles', verbose_name='角色'),
        ),
    ]
